### ISSUE TITLE
TimeInterval reads invalid length from non-UTC strings

### ISSUE THREAD

**Issue by junegunn** [arnau/ISO8601#41]
Hi, I noticed that `TimeInterval` reads invalid length from non-UTC strings since 0.10.0.

```diff
diff --git a/spec/iso8601/time_interval_spec.rb b/spec/iso8601/time_interval_spec.rb
index 00b97ee..75b5a19 100644
--- a/spec/iso8601/time_interval_spec.rb
+++ b/spec/iso8601/time_interval_spec.rb
@@ -133,10 +133,12 @@ RSpec.describe ISO8601::TimeInterval do
       pattern = 'PT1H/2010-05-09T10:30:00Z'
       pattern2 = '2010-05-09T11:30:00Z/PT1H'
       pattern3 = '2010-05-09T11:30:00Z/2010-05-09T12:30:00Z'
+      pattern4 = '2010-05-09T11:30:00+09:00/PT1H'
 
       expect(ISO8601::TimeInterval.parse(pattern).to_f).to eq(hour)
       expect(ISO8601::TimeInterval.parse(pattern2).to_f).to eq(hour)
       expect(ISO8601::TimeInterval.parse(pattern3).to_f).to eq(hour)
+      expect(ISO8601::TimeInterval.parse(pattern4).to_f).to eq(hour)
     end
 
     it "should be 0" do
```

gives

```
Failures:

  1) ISO8601::TimeInterval#to_f should calculate the size of time interval
     Failure/Error: expect(ISO8601::TimeInterval.parse(pattern4).to_f).to eq(hour)

       expected: 3600.0
            got: 36000.0

       (compared using ==)
     # ./spec/iso8601/time_interval_spec.rb:141:in `block (3 levels) in <top (required)>'
```
